services:
  web:
    build: .
    container_name: php-app
    volumes:
      - "./www:/var/www/html"
    ports:
      - 8080:80
    networks:
      - app_network
    restart: unless-stopped
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 999999
      MYSQL_USER: admin
      MYSQL_PASSWORD: AlumnadoIAW
      LANG: es_ES.UTF-8
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish2_ci
    networks:
      - app_network
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_user: admin
      PMA_PASSWORD: AlumnadoIAW
      MYSQL_ROOT_PASSWORD: 999999
      PMA_CHARSET: utf8mb4
    ports:
      - 8001:80
    depends_on:
      - db
    networks:
      - app_network
    restart: unless-stopped
  postfix:
    image: boky/postfix
    container_name: postfix
    environment:
      - ALLOWED_SENDER_DOMAINS=cineparaiso.com
      - RELAYHOST=[smtp.gmail.com]:587 
      - SMTP_USERNAME=cineparaiso.correocontacto@gmail.com
      - SMTP_PASSWORD=hrpg zywr vlnz ayiu
    networks:
      - app_network
    restart: unless-stopped
volumes:
  mysql_data:


networks:
  app_network:
